apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: example-voting-app-template
objects:
- apiVersion: v1
  data:
    database-name: db
    database-password: postgres_password
    database-user: postgres_user
  kind: Secret
  metadata:
    name: db

- apiVersion: v1
  data:
    database-password: redis_password
  kind: Secret
  metadata:
    name: redis

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: result
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'result:latest'
    postCommit: { }
    resources: { }
    runPolicy: Serial
    source:
      contextDir: /result
      git:
        ref: master
        uri: 'https://github.com/peteranton1/example-voting-app-py.git'
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: PORT
            value: '8080'
        from:
          kind: ImageStreamTag
          name: 'nodejs:10'
          namespace: openshift
      type: Source
    triggers:
      - generic:
          secret: 7410ca12c663f967
        type: Generic
      - github:
          secret: 0b9c61693e8bc4b7
        type: GitHub
      - imageChange:
          lastTriggeredImageID: >-
            172.30.1.1:5000/openshift/nodejs@sha256:3cc041334eef8d5853078a0190e46a2998a70ad98320db512968f1de0561705e
        type: ImageChange
      - type: ConfigChange

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: vote
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'vote:latest'
    postCommit: { }
    resources: { }
    runPolicy: Serial
    source:
      contextDir: /vote
      git:
        ref: master
        uri: 'https://github.com/peteranton1/example-voting-app-py.git'
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'python:3.6'
          namespace: openshift
      type: Source
    triggers:
      - generic:
          secret: 9d77d41df1161768
        type: Generic
      - github:
          secret: f9fd0c011640ea03
        type: GitHub
      - imageChange:
          lastTriggeredImageID: >-
            172.30.1.1:5000/openshift/python@sha256:ac50754646f0d37616515fb30467d8743fb12954260ec36c9ecb5a94499447e0
        type: ImageChange
      - type: ConfigChange
